{{- if .Values.obskit.metricsAuthEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obskit-service.fullname" . }}-secrets
  labels:
    {{- include "obskit-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  metricsAuthToken: {{ .Values.secrets.metricsAuthToken | default (randAlphaNum 32) | quote }}
{{- end }}

