sonar.projectKey=talaatmagdyx_obskit
sonar.organization=talaatmagdyx

# Source directories (all package src folders)
sonar.sources=packages

# Tells SonarCloud which paths are test code
sonar.tests=packages

sonar.test.inclusions=\
  packages/*/tests/**/*.py

# Exclude test folders from main source analysis
sonar.exclusions=\
  packages/*/tests/**,\
  packages/*/.venv/**,\
  packages/*/dist/**,\
  packages/*/build/**,\
  **/__pycache__/**,\
  **/*.egg-info/**

# Exclude tests from coverage analysis
# (coverage should only measure production code)
sonar.coverage.exclusions=\
  packages/*/tests/**

# Python version
sonar.python.version=3.11
