sonar.projectKey=talaatmagdyx_obskit
sonar.organization=talaatmagdyx

# Source directories
sonar.sources=src

# Tells SonarCloud which paths are test code
sonar.tests=tests

sonar.test.inclusions=\
  tests/**/*.py

# Exclude test folders from main source analysis
sonar.exclusions=\
  tests/**,\
  .venv/**,\
  dist/**,\
  build/**,\
  **/__pycache__/**,\
  **/*.egg-info/**

# Exclude tests from coverage analysis
sonar.coverage.exclusions=\
  tests/**

# Python version
sonar.python.version=3.11
